name: First Workflow
on:
  workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print hallo
      run: echo "hello world"
    - name: Print je moeder
      run: echo "je moeder"
